export enum Channel {
  WEB = 'web',
  PAYCARD = 'paycard'
}
/**
 * Configuration parameters required to initialize the Niubiz payment session.
 */
export interface INiubizConfiguration {
  /**
   * Session key generated by the backend using Niubiz's REST API.
   * It is unique per transaction and required to authorize the payment process.
   */
  sessionkey: string;

  /**
   * Defines the payment channel.
   * Use 'web' for online payments or 'paycard' for tokenization card.
   */
  channel: Channel;

  /**
   * Unique identifier assigned to the merchant by Niubiz.
   * It represents your store or business in the payment system.
   */
  merchantid: string;

  /**
   * Unique number representing the purchase transaction.
   * Must be generated by your backend and must not repeat.
   */
  purchasenumber: number;

  /**
   * Total amount of the transaction.
   * Must match the amount used when generating the session key.
   */
  amount: number;

  /**
   * Language code for the payment form UI.
   * Common values: 'ES' for Spanish, 'EN' for English.
   */
  language: string;

  /**
   * Custom font family to be used in the payment form.
   * Optional. Examples: 'Roboto', 'OpenSans'.
   */
  font: string;
}
